-- correspondenceAuditLog.id must always be an automatically generated primary key.
--
-- Diagnosis (read-only, production, PostgreSQL 16.14):
--   * id            bigint NOT NULL, PRIMARY KEY (id)
--   * is_identity   YES / BY DEFAULT          (attidentity = 'd')
--   * column_default NULL                     (identity columns have no pg_attrdef
--                                              row — this is why it *looked* like a
--                                              missing default during the audit)
--   * sequence      public."correspondenceAuditLog_id_seq", owned through the
--                   identity (pg_depend.deptype = 'i'),
--                   last_value = 1740 > max(id) = 1739
--
-- ROOT CAUSE of the observed 23502: production is healthy — an ordinary INSERT
-- without id already generates one, so correspondenceDirectories,
-- correspondenceWorkflow and correspondenceTariffs already work. The failure came
-- from a throwaway fixture that recreated the column as a plain bigint. The real
-- defect is that the invariant "id always auto-generates" was never guaranteed by
-- a migration; it held only because an identity had been created by hand.
--
-- This migration therefore changes nothing on the current production schema. It
-- makes the invariant explicit and self-healing for the two shapes that break it:
--   (A) id is not an identity yet                     -> ADD GENERATED BY DEFAULT
--   (B) its sequence lags behind max(id) / is fresh   -> move it past the data
--
-- It never touches a row: no UPDATE, no DELETE, no INSERT, no renumbering, and no
-- business table is referenced. Safe when the table is empty, when it holds ids,
-- and on repeated runs.

DO $migration$
DECLARE
  v_identity text;
  v_seq      text;
  v_last     bigint;
  v_called   boolean;
  v_max      bigint;
BEGIN
  IF to_regclass('public."correspondenceAuditLog"') IS NULL THEN
    RAISE NOTICE 'correspondenceAuditLog does not exist in this database; nothing to do';
    RETURN;
  END IF;

  SELECT attidentity INTO v_identity
    FROM pg_attribute
   WHERE attrelid = 'public."correspondenceAuditLog"'::regclass
     AND attname = 'id';

  -----------------------------------------------------------------------------
  -- (A) Make the column generate ids when it does not yet.
  -----------------------------------------------------------------------------
  IF v_identity = '' OR v_identity IS NULL THEN
    -- A previous partial run may have left the conventionally named sequence
    -- behind without attaching it. Drop it so PostgreSQL names the real identity
    -- sequence after the table instead of inventing a "_seq1" sibling. The drop is
    -- refused whenever anything else depends on the sequence, and when it is
    -- already the audit column's sequence.
    IF to_regclass('public."correspondenceAuditLog_id_seq"') IS NOT NULL
       AND NOT EXISTS (
         SELECT 1 FROM pg_depend
          WHERE objid = to_regclass('public."correspondenceAuditLog_id_seq"')
            AND refobjid = 'public."correspondenceAuditLog"'::regclass
            AND deptype IN ('a', 'i')
       )
       AND NOT EXISTS (
         SELECT 1 FROM pg_depend
          WHERE refobjid = to_regclass('public."correspondenceAuditLog_id_seq"')
       ) THEN
      DROP SEQUENCE "correspondenceAuditLog_id_seq";
    END IF;

    EXECUTE 'ALTER TABLE "correspondenceAuditLog" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;

  -----------------------------------------------------------------------------
  -- (B) Never reuse an id that already exists. A freshly created sequence has
  -- is_called = false and would hand out 1, colliding with the existing PK.
  -- Existing rows themselves are not modified in any way.
  -----------------------------------------------------------------------------
  v_seq := pg_get_serial_sequence('"correspondenceAuditLog"', 'id');
  IF v_seq IS NULL THEN
    RAISE EXCEPTION 'correspondenceAuditLog.id has no sequence after migration';
  END IF;

  SELECT COALESCE(max("id"), 0) INTO v_max FROM "correspondenceAuditLog";
  EXECUTE format('SELECT last_value, is_called FROM %s', v_seq) INTO v_last, v_called;

  IF v_max > 0 AND (NOT v_called OR v_last < v_max) THEN
    EXECUTE format('ALTER SEQUENCE %s RESTART WITH %s', v_seq, v_max);
  END IF;

  -- is_called must be true so the next generated id is v_max + 1 (or the current
  -- value + 1 when the sequence is already ahead).
  EXECUTE format('SELECT setval(%L, GREATEST((SELECT COALESCE(max("id"), 0) FROM "correspondenceAuditLog"), (SELECT last_value FROM %s)), true)', v_seq, v_seq);
END
$migration$;

-- Post-check (read-only):
--   SELECT is_identity, identity_generation FROM information_schema.columns
--    WHERE table_name = 'correspondenceAuditLog' AND column_name = 'id';   -- YES / BY DEFAULT
--
--   SELECT pg_get_serial_sequence('"correspondenceAuditLog"', 'id');        -- exactly one sequence
--   SELECT last_value, is_called FROM "correspondenceAuditLog_id_seq";      -- >= max(id), true
--   SELECT count(*) FROM "correspondenceAuditLog";                          -- unchanged
--
--   -- and an ordinary INSERT now returns a generated id:
--   INSERT INTO "correspondenceAuditLog" ("managerId","action","entityType","entityId")
--   VALUES (1,'check','check',0) RETURNING id;
