CREATE TABLE `requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`createdByUserId` int NOT NULL,
	`requestType` enum('delivery','movement','nuts','courier_call','pickup_from_tc','simple') NOT NULL,
	`requestStatus` enum('pending','assigned','in_progress','completed','cancelled') NOT NULL DEFAULT 'pending',
	`courierId` int,
	`clientId` int,
	`recipientName` varchar(255),
	`recipientPhone` varchar(20),
	`deliveryAddress` text,
	`deliveryCity` varchar(100),
	`packageDescription` text,
	`packageType` enum('document','small','medium','large','fragile'),
	`placesCount` int DEFAULT 1,
	`senderName` varchar(255),
	`senderAddress` text,
	`senderPhone` varchar(20),
	`items` text,
	`callReason` text,
	`tcName` varchar(255),
	`tcAddress` text,
	`trackingNumber` varchar(100),
	`description` text,
	`specialInstructions` text,
	`deliveryTimeFrom` varchar(5),
	`deliveryTimeTo` varchar(5),
	`estimatedMinutes` int,
	`scheduledAt` timestamp,
	`acceptedAt` timestamp,
	`completedAt` timestamp,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `requests_id` PRIMARY KEY(`id`)
);
